api/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url, include
from api.views import ClienteViewSet
from rest_framework import routers


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'apiv01cliente', ClienteViewSet)

urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       )

mtvmcotizacionv02/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from mtvmcotizacionv02 import views

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from api.views import ClienteViewSet, PaisViewSet, \
    ProvinciaViewSet, TipoDeClienteViewSet, \
    CiudadViewSet, BarrioViewSet, CalleViewSet, \
    DireccionViewSet


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'api/v1/tipodecliente', TipoDeClienteViewSet)
router.register(r'api/v1/cliente', ClienteViewSet)
router.register(r'api/v1/pais', PaisViewSet)
router.register(r'api/v1/provincia', ProvinciaViewSet)
router.register(r'api/v1/ciudad', CiudadViewSet)
router.register(r'api/v1/barrio', BarrioViewSet)
router.register(r'api/v1/calle', CalleViewSet)
router.register(r'api/v1/direccion', DireccionViewSet)

urlpatterns = [
    url(r'^$', views.pantalla_inicial,
        name='pantalla_inicial'),
    url(r'^guia_de_estilo/',
        views.guia_de_estilo,
        name='guia_de_estilos'),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^direccion/',
        include('direccion.urls',
                namespace="udirecciones")),
    url(r'^ambiente/',
        include('ambiente.urls',
                namespace="uambientes")),
    url(r'^cliente/',
        include('cliente.urls',
                namespace="uclientes")),
    url(r'^contenedor/',
        include('contenedor.urls',
                namespace="ucontenedores")),
    url(r'^mueble/',
        include('mueble.urls',
                namespace="umuebles")),
    url(r'^gestiondedocumento/',
        include('gestiondedocumento.urls',
                namespace="ugestiondedocumentos")),
    url(r'^estadoderegistro/',
        include('estadoderegistro.urls',
                namespace="uestadoderegistros")),
    url(r'^complejidadriesgo/',
        include('complejidadriesgo.urls',
                namespace="ucomplejidadriesgos")),
    url(r'^mensaje/',
        include('mensaje.urls',
                namespace="umensajes")),
    url(r'^premisas/',
        include('premisas.urls',
                namespace="upremisas")),
    url(r'^promocion/',
        include('promocion.urls',
                namespace="upromociones")),
    url(r'^menu/',
        include('menu.urls',
                namespace="umenus")),
    url(r'^herramienta/',
        include('herramienta.urls',
                namespace="uherramientas")),
    url(r'^material/',
        include('material.urls',
                namespace="umateriales")),
    url(r'^servicio/',
        include('servicio.urls',
                namespace="uservicios")),
    url(r'^talonario/',
        include('talonario.urls',
                namespace="utalonarios")),
    url(r'^trabajador/',
        include('trabajador.urls',
                namespace="utrabajadores")),
    url(r'^vehiculo/',
        include('vehiculo.urls',
                namespace="uvehiculos")),
    url(r'^widget/',
        include('widget.urls',
                namespace="uwidgets")),
    url(r'^cotizacionweb/',
        include('cotizacionweb.urls',
                namespace="ucotizacionesweb")),
    url(r'^almacen/',
        include('almacen.urls',
                namespace="ualmacenes")),
    url(r'^cotizador/',
        include('cotizador.urls',
                namespace="ucotizadores")),
    url(r'^usuario/',
        include('usuario.urls',
                namespace="uusuarios")),
    url(r'^notificacion/',
        include('notificacion.urls',
                namespace="unotificaciones")),
    url(r'^api/',
        include('api.urls',
                namespace="uapis")),
    url(r'^chaining/',
        include('smart_selects.urls')),
    url(r'^sidebarUpdate/$',
        'mtvmcotizacionv02.views.sidebarUpdate',
        name='sidebarUpdate'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls',
                namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^static/(?P<path>.*)$',
                                'django.views.static.serve',
                                {'document_root': settings.STATICFILES_DIRS}),)

talonario/urls.py
"""
Docstring pendiente para este documento
"""

from django.conf.urls import patterns, url
from talonario.views import TipoDeDocumentoImpresoListView, \
    TipoDeDocumentoImpresoView, TipoDeDocumentoImpresoUpdate, \
    TipoDeDocumentoImpresoDelete, TalonarioListView, TalonarioView, \
    TalonarioUpdate, TalonarioDelete, DocumentoDelTalonarioListView, \
    DocumentoDelTalonarioView, DocumentoDelTalonarioUpdate, \
    DocumentoDelTalonarioDelete, TrazabilidadTalonarioListView


urlpatterns = patterns('',
                       url(r'^$',
                           TalonarioListView.as_view(),
                           name='list_talonario'),
                       url(r'^nuevo/',
                           TalonarioView.as_view(),
                           name='add_talonario'),
                       url(r'^editar/(?P<pk>\d+)/$',
                           TalonarioUpdate.as_view(),
                           name='edit_talonario'),
                       url(r'^eliminar/(?P<pk>\d+)/$',
                           TalonarioDelete.as_view(),
                           name='eliminar_talonario'),
                       url(r'^tipo_de_documento/$',
                           TipoDeDocumentoImpresoListView.as_view(),
                           name='list_tipodedocumentoimpreso'),
                       url(r'^tipo_de_documento/nuevo/',
                           TipoDeDocumentoImpresoView.as_view(),
                           name='add_tipodedocumentoimpreso'),
                       url(r'^tipo_de_documento/editar/(?P<pk>\d+)/$',
                           TipoDeDocumentoImpresoUpdate.as_view(),
                           name='edit_tipodedocumentoimpreso'),
                       url(r'^tipo_de_documento/eliminar/(?P<pk>\d+)/$',
                           TipoDeDocumentoImpresoDelete.as_view(),
                           name='eliminar_tipodedocumentoimpreso'),
                       url(r'^documento_del_talonario/$',
                           DocumentoDelTalonarioListView.as_view(),
                           name='list_documentodeltalonario'),
                       url(r'^documento_del_talonario/nuevo/',
                           DocumentoDelTalonarioView.as_view(),
                           name='add_documentodeltalonario'),
                       url(r'^documento_del_talonario/editar/(?P<pk>\d+)/$',
                           DocumentoDelTalonarioUpdate.as_view(),
                           name='edit_documentodeltalonario'),
                       url(r'^documento_del_talonario/eliminar/(?P<pk>\d+)/$',
                           DocumentoDelTalonarioDelete.as_view(),
                           name='eliminar_documentodeltalonario'),
                       url(r'^trazabilidad_talonario/$',
                           TrazabilidadTalonarioListView.as_view(),
                           name='list_trazabilidadtalonario'),
                       )

talonario/models.py
from django.db import models
from estadoderegistro.models import EstadoDeRegistro
from django.contrib.auth.models import User


# Create your models here.
class TipoDeDocumentoImpreso(models.Model):
    """docstring for TipoDeDocumentoImpreso"""
    def __init__(self, *args, **kwargs):
        super(TipoDeDocumentoImpreso, self).__init__(*args, **kwargs)

    tipo_de_documento_impreso = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.tipo_de_documento_impreso

    class Meta:
        verbose_name = "Tipo de documento impreso"
        verbose_name_plural = "Tipos de documento impreso"
        ordering = ["tipo_de_documento_impreso"]


class Talonario(models.Model):
    """docstring for Talonario"""
    def __init__(self, *args, **kwargs):
        super(Talonario, self).__init__(*args, **kwargs)

    talonario = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    prefijo = models.CharField(max_length=10, blank=True)
    separador = models.CharField(max_length=10, blank=True)
    numero_desde = models.CharField(max_length=50)
    numero_hasta = models.CharField(max_length=50)
    separado_sufijo = models.CharField(max_length=10, blank=True)
    sufijo = models.CharField(max_length=10, blank=True)
    numeracion_correlativa = models.BooleanField(default=None)
    numero_de_documento = models.IntegerField()
    tipo_de_documento_impreso = models.ForeignKey(TipoDeDocumentoImpreso)
    cantidad_fija = models.BooleanField(default=None)

    def __str__(self):
        return self.talonario

    class Meta:
        verbose_name = "Talonario"
        verbose_name_plural = "Talonarios"
        ordering = ["talonario"]


class DocumentoDelTalonario(models.Model):
    """docstring for DocumentoDelTalonario"""
    def __init__(self, *args, **kwargs):
        super(DocumentoDelTalonario, self).__init__(*args, **kwargs)

    talonario = models.ForeignKey(Talonario)
    numero = models.CharField(max_length=50)
    estado = models.CharField(max_length=10)
    informacion_de_proceso = models.TextField()
    informacion_de_beneficiario = models.TextField()
    numero_final = models.CharField(max_length=250)

    def __str__(self):
        return u' %s - %s' % (self.talonario, self.numero)

    class Meta:
        verbose_name = "Documento del talonario"
        verbose_name_plural = "Documentos del talonario"
        ordering = ["talonario", "numero"]


class TalonarioEstado(models.Model):
    """docstring for TalonarioEstado"""
    def __init__(self, *args, **kwargs):
        super(TalonarioEstado, self).__init__(*args, **kwargs)

    talonario = models.ForeignKey(Talonario)
    estado_de_documento = models.ForeignKey(EstadoDeRegistro)
    fecha_registro = models.DateField(auto_now_add=True)
    usuario = models.ForeignKey(User)
    observacion = models.TextField(blank=True)
    predefinido = models.BooleanField(default=None)

    def __str__(self):
        return u' %s - %s' % (self.talonario, self.estado_de_documento)

    class Meta:
        verbose_name = "Estado del talonario"
        verbose_name_plural = "Estados de los talonarios"
        ordering = ["talonario", "estado_de_documento"]


class TrazabilidadTalonario(models.Model):
    """docstring for TrazabilidadTalonario"""
    def __init__(self, *args, **kwargs):
        super(TrazabilidadTalonario, self).__init__(*args, **kwargs)

    talonario = models.ForeignKey(Talonario)
    fecha_registro = models.DateField(auto_now_add=True)
    fecha_modificacion = models.DateField(null=True, blank=True)
    usuario = models.ForeignKey(User)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = "Trazabilidad del talonario"
        verbose_name_plural = "Trazabilidad de los talonarios"


class DocumentoDelTalonarioEstado(models.Model):
    """docstring for DocumentoDelTalonarioEstado"""
    def __init__(self, *args, **kwargs):
        super(DocumentoDelTalonarioEstado, self).__init__(*args, **kwargs)

    documento_del_talonario = models.ForeignKey(DocumentoDelTalonario)
    estado_de_documento = models.ForeignKey(EstadoDeRegistro)
    fecha_registro = models.DateField(auto_now_add=True)
    usuario = models.ForeignKey(User)
    observacion = models.TextField(blank=True)
    predefinido = models.BooleanField(default=None)

    def __str__(self):
        return u' %s - %s' % (self.documento_del_talonario, self.estado_de_documento)

    class Meta:
        verbose_name = "Estado del documento del talonario"
        verbose_name_plural = "Estados de los documentos de los talonarios"
        ordering = ["documento_del_talonario", "estado_de_documento"]

talonario/forms.py
"""
Docstring documentación pendiente

"""
from talonario.models import TipoDeDocumentoImpreso, Talonario, \
    DocumentoDelTalonario
from base.forms import BaseFormMd, SelectMD, Select
from djangular.forms import NgModelFormMixin, NgModelForm
from django.forms.models import inlineformset_factory
from django.forms import ModelForm, TextInput, Textarea


class TipoDeDocumentoImpresoForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = TipoDeDocumentoImpreso
        fields = '__all__'
        widgets = {
            'tipo_de_documento_impreso': TextInput(attrs={'required': 'required', 'tabindex':'1'}),
            'descripcion': Textarea(attrs={'required': 'required', 'tabindex': '2', 'cols': '1', 'rows': '1'})
            }
        labels = {
            'tipo_de_documento_impreso': ('Nombre del tipo de mueble'),
            'descripcion': ('Descripción del tipo de mueble')
            }


class TalonarioForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = Talonario
        fields = 'tipo_de_documento_impreso', \
                 'talonario', \
                 'descripcion', \
                 'prefijo', \
                 'separador', \
                 'numero_desde', \
                 'numero_hasta', \
                 'separado_sufijo', \
                 'numeracion_correlativa', \
                 'numero_de_documento', \
                 'cantidad_fija'
        labels = {
            'talonario': ('Nombre del talonario'),
            'descripcion': ('Descripción del talonario'),
            'cantidad_fija': ('Cantidad fija del talonario')
        }
        widgets = {
            'tipo_de_documento_impreso': Select(attrs={'tabindex': '1'}),
            'descripcion': Textarea(attrs={'required': 'required', 'tabindex': '2', 'cols': '1', 'rows': '1'})
            }


class DocumentoDelTalonarioForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = DocumentoDelTalonario
        fields = '__all__'
        labels = {
            'talonario': ('Nombre del talonario'),
            'numero': ('Numero del talonario'),
            'estado': ('Estado del talonario'),
            'informacion_de_proceso': ('Información de proceso del talonario'),
            'informacion_de_beneficiari': ('Información de beneficiara del talonario'),
            'numero_final': ('Numero final del talonario')
        }
        widgets = {
            'talonario': Select(attrs={'tabindex': '1'})
            }

talonario/templates/documentodeltalonario_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha del documento del talonario: {{form.numero.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if documentodeltalonario_previous %}

<li class="anterior">
    <a href="{% url 'utalonarios:edit_documentodeltalonario' documentodeltalonario_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a>
</li>

{% endif %}

{% if documentodeltalonario_next %}

<li class="siguiente">
    <a href="{% url 'utalonarios:edit_documentodeltalonario' documentodeltalonario_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
    $(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
    $(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
    var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
    var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
    var pos = $(tr).position();
    tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.numero.value}}');
    tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.estado.value}}');
    tr.children('td[id=td3_{{form.instance.pk}}]').text('{{form.informacion_de_proceso.value}}');
    tr.children('td[id=td4_{{form.instance.pk}}]').text('{{form.informacion_de_beneficiari.value}}');
    tr.children('td[id=td5_{{form.instance.pk}}]').text('{{form.numero_final.value}}');
    tr.children('td[id=td6_{{form.instance.pk}}]').text('{{documentodeltalonario.talonario}}');
    $(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
</script>

{% endblock jsFicha %}

talonario/templates/tipodedocumentoimpreso_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha del tipo de documento impreso: {{form.tipo_de_documento_impreso.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if tipodedocumentoimpreso_previous %}

<li class="anterior">
    <a href="{% url 'utalonarios:edit_tipodedocumentoimpreso' tipodedocumentoimpreso_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado"><a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a></li>

{% endif %}

{% if tipodedocumentoimpreso_next %}

<li class="siguiente">
    <a href="{% url 'utalonarios:edit_tipodedocumentoimpreso' tipodedocumentoimpreso_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
var pos = $(tr).position();
tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.tipo_de_documento_impreso.value}}');
tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.descripcion.value|truncatechars:"30"}}');
$(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
</script>

{% endblock jsFicha %}

talonario/templates/tipodedocumentoimpreso_lista.html
{% extends "base_lista.html" %}

{% block titulo %}

Talonario

{% endblock titulo %}

{% block titulo_lista %}

<h2>Listado de tipos de documentos impresos</h2>
 <h6>Cantidad de tipos de documentos impresos encontrados:
    <span class="numRegistro" id="count_reg">

        {{ tipodedocumentoimpresos.count }}

    </span>
</h6>

{% endblock titulo_lista %}

{% block paginacion_lista %}

{% if request.GET.page == "0" %}

<li><a href="?page=1">Paginar</a></li>

{% else %}

{% if page_obj.has_previous %}

{% if request.GET.order_by %}

<li>
  <a href="?page={{ page_obj.previous_page_number }}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li>
  <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
  <a href="#" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
  <a href="#" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% endif %}

{% if request.GET.page == "1" %}

<li class="btn-disabled">
  <a href="?page=1&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">Primero...</a>
</li>

{% else %}

<li class="">
  <a href="?page=1&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">Primero...</a>
</li>

{% endif %}

{% for p in page_range2 %}

{% if p == page_obj.number %}

<li class="active">
  <a href="?page={{p}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">{{p}}</a>
</li>

{% else %}

<li>
  <a href="?page={{p}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">{{p}}</a>
</li>

{% endif %}

{% endfor %}

{% if page_obj.paginator.num_pages %}

{% if request.GET.page == ultimo %}

<li class="btn-disabled">
  <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">...Ultimo</a>
</li>

{% else %}

<li class="">
  <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">...Ultimo</a>
</li>

{% endif %}

{% endif %}

{% if page_obj.has_next %}

{% if request.GET.order_by %}

<li>
  <a href="?page={{ page_obj.next_page_number }}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li>
  <a href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
  <a href="#" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
  <a href="#" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% endif %}

<li><a href="?page=0" tabindex="-1">Ver todo</a></li>

{% endif %}

{% endblock paginacion_lista %}

{% block lista %}

{% if tipodedocumentoimpresos %}

<tr class="active">
    <th>
        Nombre del tipo de documento impreso

        {% if request.GET.page %}

        {% if request.GET.order_by == "tipo_de_documento_impreso" %}

        <a href="?order_by=-tipo_de_documento_impreso&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-tipo_de_documento_impreso"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=tipo_de_documento_impreso&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="tipo_de_documento_impreso" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% else %}

        {% if request.GET.order_by == "tipo_de_documento_impreso" %}

        <a href="?order_by=-tipo_de_documento_impreso&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-tipo_de_documento_impreso"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=tipo_de_documento_impreso&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="tipo_de_documento_impreso" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% endif %}

    </th>
    <th>
        Descripción del tipo de documento impreso

        {% if request.GET.page %}

        {% if request.GET.order_by == "descripcion" %}

        <a href="?order_by=-descripcion&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-descripcion"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=descripcion&page={{request.GET.page}}" id="descripcion" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% else %}

        {% if request.GET.order_by == "descripcion" %}

        <a href="?order_by=-descripcion{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-descripcion"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=descripcion{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="descripcion" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% endif %}

    </th>
</tr>
<tbody>
{% for i in tipodedocumentoimpresos %}

<tr id="tr{{i.pk}}" data-url="{% url 'utalonarios:edit_tipodedocumentoimpreso' i.pk %}?next={{request.get_full_path}}" class="btnFicha">
    <td id="td1_{{i.pk}}">

        {{ i.tipo_de_documento_impreso }}

    </td>
    <td id="td2_{{i.pk}}">

      {{ i.descripcion|truncatechars:"30" }}

    </td>
    <td class="c_td">
      <a title="Eliminar" data-toggletooltip="tooltip" data-placement="left" data-url="{% url 'utalonarios:eliminar_tipodedocumentoimpreso' i.pk %}?next={{request.get_full_path}}" data-id="{{ i.id }}" data-nombre="{{ i.tipodedocumentoimpresos }}" class="iconoRemover btnEliminar" data-toggle="modal" data-target="#modalEliminar" id="eliminar{{i.id}}"></a>
      <span class="iconoGrupoControl"></span>
    </td>
</tr>

{% endfor %}

{% else %}

<tr>
    <td> No se encontraron registros</td>
</tr>

{% endif %}

{% endblock lista %}