api/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url, include
from api.views import ClienteViewSet
from rest_framework import routers


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'apiv01cliente', ClienteViewSet)

urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       )

mtvmcotizacionv02/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from mtvmcotizacionv02 import views

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from api.views import ClienteViewSet, PaisViewSet, \
    ProvinciaViewSet, TipoDeClienteViewSet, \
    CiudadViewSet, BarrioViewSet, CalleViewSet, \
    DireccionViewSet


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'api/v1/tipodecliente', TipoDeClienteViewSet)
router.register(r'api/v1/cliente', ClienteViewSet)
router.register(r'api/v1/pais', PaisViewSet)
router.register(r'api/v1/provincia', ProvinciaViewSet)
router.register(r'api/v1/ciudad', CiudadViewSet)
router.register(r'api/v1/barrio', BarrioViewSet)
router.register(r'api/v1/calle', CalleViewSet)
router.register(r'api/v1/direccion', DireccionViewSet)

urlpatterns = [
    url(r'^$', views.pantalla_inicial,
        name='pantalla_inicial'),
    url(r'^guia_de_estilo/',
        views.guia_de_estilo,
        name='guia_de_estilos'),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^direccion/',
        include('direccion.urls',
                namespace="udirecciones")),
    url(r'^ambiente/',
        include('ambiente.urls',
                namespace="uambientes")),
    url(r'^cliente/',
        include('cliente.urls',
                namespace="uclientes")),
    url(r'^contenedor/',
        include('contenedor.urls',
                namespace="ucontenedores")),
    url(r'^mueble/',
        include('mueble.urls',
                namespace="umuebles")),
    url(r'^gestiondedocumento/',
        include('gestiondedocumento.urls',
                namespace="ugestiondedocumentos")),
    url(r'^estadoderegistro/',
        include('estadoderegistro.urls',
                namespace="uestadoderegistros")),
    url(r'^complejidadriesgo/',
        include('complejidadriesgo.urls',
                namespace="ucomplejidadriesgos")),
    url(r'^mensaje/',
        include('mensaje.urls',
                namespace="umensajes")),
    url(r'^premisas/',
        include('premisas.urls',
                namespace="upremisas")),
    url(r'^promocion/',
        include('promocion.urls',
                namespace="upromociones")),
    url(r'^menu/',
        include('menu.urls',
                namespace="umenus")),
    url(r'^herramienta/',
        include('herramienta.urls',
                namespace="uherramientas")),
    url(r'^material/',
        include('material.urls',
                namespace="umateriales")),
    url(r'^servicio/',
        include('servicio.urls',
                namespace="uservicios")),
    url(r'^talonario/',
        include('talonario.urls',
                namespace="utalonarios")),
    url(r'^trabajador/',
        include('trabajador.urls',
                namespace="utrabajadores")),
    url(r'^vehiculo/',
        include('vehiculo.urls',
                namespace="uvehiculos")),
    url(r'^widget/',
        include('widget.urls',
                namespace="uwidgets")),
    url(r'^cotizacionweb/',
        include('cotizacionweb.urls',
                namespace="ucotizacionesweb")),
    url(r'^almacen/',
        include('almacen.urls',
                namespace="ualmacenes")),
    url(r'^cotizador/',
        include('cotizador.urls',
                namespace="ucotizadores")),
    url(r'^usuario/',
        include('usuario.urls',
                namespace="uusuarios")),
    url(r'^notificacion/',
        include('notificacion.urls',
                namespace="unotificaciones")),
    url(r'^api/',
        include('api.urls',
                namespace="uapis")),
    url(r'^chaining/',
        include('smart_selects.urls')),
    url(r'^sidebarUpdate/$',
        'mtvmcotizacionv02.views.sidebarUpdate',
        name='sidebarUpdate'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls',
                namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^static/(?P<path>.*)$',
                                'django.views.static.serve',
                                {'document_root': settings.STATICFILES_DIRS}),)

mueble/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url
from mueble.views import TipoDeMuebleListView, TipoDeMuebleView, \
    TipoDeMuebleUpdate, TipoDeMuebleDelete, MuebleListView, \
    MuebleView, MuebleUpdate, MuebleDelete, EspecificacionDeMuebleListView, \
    EspecificacionDeMuebleView, EspecificacionDeMuebleUpdate, \
    EspecificacionDeMuebleDelete, MueblePorAmbienteListView, \
    MueblePorAmbienteView, MueblePorAmbienteUpdate, MueblePorAmbienteDelete


urlpatterns = patterns('',
                       url(r'^$',
                           MuebleListView.as_view(),
                           name='list_mueble'),
                       url(r'^nuevo',
                           MuebleView.as_view(),
                           name='add_mueble'),
                       url(r'^editar/(?P<pk>\d+)/$',
                           MuebleUpdate.as_view(),
                           name='edit_mueble'),
                       url(r'^eliminar/(?P<pk>\d+)/$',
                           MuebleDelete.as_view(),
                           name='eliminar_mueble'),
                       url(r'^tipo_de_mueble/$',
                           TipoDeMuebleListView.as_view(),
                           name='list_tipodemueble'),
                       url(r'^tipo_de_mueble/nuevo',
                           TipoDeMuebleView.as_view(),
                           name='add_tipodemueble'),
                       url(r'^tipo_de_mueble/editar/(?P<pk>\d+)/$',
                           TipoDeMuebleUpdate.as_view(),
                           name='edit_tipodemueble'),
                       url(r'^tipo_de_mueble/eliminar/(?P<pk>\d+)/$',
                           TipoDeMuebleDelete.as_view(),
                           name='eliminar_tipodemueble'),
                       url(r'^especificacion_de_mueble/$',
                           EspecificacionDeMuebleListView.as_view(),
                           name='list_especificaciondemueble'),
                       url(r'^especificacion_de_mueble/nuevo',
                           EspecificacionDeMuebleView.as_view(),
                           name='add_especificaciondemueble'),
                       url(r'^especificacion_de_mueble/editar/(?P<pk>\d+)/$',
                           EspecificacionDeMuebleUpdate.as_view(),
                           name='edit_especificaciondemueble'),
                       url(r'^especificacion_de_mueble/eliminar/(?P<pk>\d+)/$',
                           EspecificacionDeMuebleDelete.as_view(),
                           name='eliminar_especificaciondemueble'),
                       url(r'^mueble_por_ambiente/$',
                           MueblePorAmbienteListView.as_view(),
                           name='list_muebleporambiente'),
                       url(r'^mueble_por_ambiente/nuevo',
                           MueblePorAmbienteView.as_view(),
                           name='add_muebleporambiente'),
                       url(r'^mueble_por_ambiente/editar/(?P<pk>\d+)/$',
                           MueblePorAmbienteUpdate.as_view(),
                           name='edit_muebleporambiente'),
                       url(r'^mueble_por_ambiente/eliminar/(?P<pk>\d+)/$',
                           MueblePorAmbienteDelete.as_view(),
                           name='eliminar_muebleporambiente'),
                       )

mueble/models.py
"""
docstring

Documentacion del proyecto

"""
from django.db import models
from ambiente.models import AmbientePorTipoDeInmueble


# Create your models here.
class TipoDeMueble(models.Model):
    """docstring for TipoDeMueble"""
    def __init__(self, *args, **kwargs):
        super(TipoDeMueble, self).__init__(*args, **kwargs)
    tipo_de_mueble = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.tipo_de_mueble

    class Meta:
        verbose_name = "Tipo de mueble"
        verbose_name_plural = "Tipos de mueble"
        ordering = ['tipo_de_mueble']


class Mueble(models.Model):
    """docstring for Mueble"""
    def __init__(self, *args, **kwargs):
        super(Mueble, self).__init__(*args, **kwargs)
    mueble = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True)
    tipo_de_mueble = models.ForeignKey(TipoDeMueble, on_delete=models.PROTECT)
    trasladable = models.BooleanField(default=None)
    fragil = models.BooleanField(default=None)
    pesado = models.BooleanField(default=None)
    contenido_fragil = models.BooleanField(default=None)
    contenido_textil = models.BooleanField(default=None)

    def __str__(self):
        return self.mueble

    class Meta:
        verbose_name = "Mueble"
        verbose_name_plural = "Muebles"
        ordering = ['mueble']


class EspecificacionDeMueble(models.Model):
    """docstring for EspecificacionDeMueble"""
    def __init__(self, *args, **kwargs):
        super(EspecificacionDeMueble, self).__init__(*args, **kwargs)
    mueble = models.ForeignKey(Mueble, on_delete=models.PROTECT)
    especificacion_de_mueble = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    ancho = models.DecimalField(max_digits=7, decimal_places=2)
    largo = models.DecimalField(max_digits=7, decimal_places=2)
    alto = models.DecimalField(max_digits=7, decimal_places=2)
    volumen_en_camion = models.IntegerField()
    predefinido = models.BooleanField(default=None)

    def __str__(self):
        return self.especificacion_de_mueble

    def _get_volumendemueble(self):
        return round((self.ancho*self.alto*self.largo), 2)
    volumen_de_mueble = property(_get_volumendemueble)

    class Meta:
        verbose_name = "Especificación del mueble"
        verbose_name_plural = "Especificaciones del mueble"
        ordering = ['especificacion_de_mueble']


class MueblePorAmbiente(models.Model):
    """docstring for MueblePorAmbiente"""
    def __init__(self, *args, **kwargs):
        super(MueblePorAmbiente, self).__init__(*args, **kwargs)
    especificacion_de_mueble = models.ForeignKey(EspecificacionDeMueble, on_delete=models.PROTECT)
    ambiente_por_tipo_de_inmueble = models.ForeignKey(AmbientePorTipoDeInmueble, on_delete=models.PROTECT)
    predefinido = models.BooleanField(default=None)

    def __str__(self):
        return u' %s - %s' % (self.especificacion_de_mueble, self.ambiente_por_tipo_de_inmueble)

    class Meta:
        verbose_name = "Mueble por ambiente"
        verbose_name_plural = "Muebles por ambientes"
        ordering = ['especificacion_de_mueble', 'ambiente_por_tipo_de_inmueble']

mueble/forms.py
"""
Docstring documentación pendiente

"""

from django.forms import ModelForm, TextInput, Textarea, Select
from mueble.models import TipoDeMueble, Mueble, \
    EspecificacionDeMueble, MueblePorAmbiente
from djangular.forms import NgModelFormMixin, NgModelForm
from djangular.forms.widgets import CheckboxChoiceInput
from base.forms import BaseFormMd, SelectMD, Checkbox, selectSearchMD
#from djangular.forms import CheckboxChoiceInput, CheckboxFieldRenderer, CheckboxFieldRendererMixin
#from django.forms.forms import _html_output
from django.forms.widgets import CheckboxFieldRenderer
from django import forms


class TipoDeMuebleForm(ModelForm):
    class Meta:
        model = TipoDeMueble
        fields = '__all__'
        widgets = {
            'tipo_de_mueble': TextInput(attrs={'required': 'required', 'tabindex':'1'}),
            'descripcion': Textarea(attrs={'required': 'required', 'tabindex': '2', 'cols': '1', 'rows': '1'}),
            }
        labels = {
            'descripcion': ('Descripción del tipo de mueble'),
            'tipo_de_mueble': ('Nombre del tipo de mueble')
            }


class MuebleForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    def __init__(self, *args, **kwargs):
        super(MuebleForm, self).__init__(*args, **kwargs)
        self.fields['tipo_de_mueble'].empty_label = 'Seleccione un tipo de mueble'

    class Meta:
        model = Mueble
        fields = '__all__'
        widgets = {
            'tipo_de_mueble': Select(attrs={'required': 'required', 'tabindex': '1', 'ng-change': 'onChange()'}),
            'mueble': TextInput(attrs={'required': 'required', 'tabindex': '2'}),
            'descripcion': Textarea(attrs={'required': 'required', 'tabindex': '3', 'cols': '1', 'rows': '1'}),
            'trasladable': Checkbox(attrs={'tabindex': '4'}),
            'fragil': Checkbox(attrs={'tabindex': '5'}),
            'pesado': Checkbox(attrs={'tabindex': '6'}),
            'contenido_fragil': Checkbox(attrs={'tabindex': '7'}),
            'contenido_textil': Checkbox(attrs={'tabindex': '8'}),
            }
        labels = {
            'tipo_de_mueble': ('Tipo de mueble asociado'),
            'mueble': ('Nombre del mueble'),
            'descripcion': ('Descripción del mueble'),
            'trasladable': ('¿Mueble trasladable?'),
            'fragil': ('¿Mueble fragil?'),
            'pesado': ('¿Mueble pesado?'),
            'contenido_fragil': ('¿Posee contenido fragil?'),
            'contenido_textil': ('¿Posee contenido textil?')
            }


class EspecificacionDeMuebleForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    def __init__(self, *args, **kwargs):
        super(EspecificacionDeMuebleForm, self).__init__(*args, **kwargs)
        self.fields['mueble'].empty_label = 'Seleccione un mueble'

    class Meta:
        model = EspecificacionDeMueble
        fields = '__all__'
        widgets = {
            'mueble': Select(attrs={'required': 'required', 'tabindex': '1', 'ng-change': 'onChange()'}),
            'especificacion_de_mueble': TextInput(attrs={'required': 'required', 'tabindex': '2'}),
            'descripcion': Textarea(attrs={'required': 'required', 'tabindex': '3', 'cols': '1', 'rows': '1'}),
            'predefinido': Checkbox(attrs={'tabindex': '8'}),
        }
        labels = {
            'mueble': ('Nombre del mueble asociado'),
            'especificacion_de_mueble': ('Especificación del mueble'),
            'descripcion': ('Descripción de la especificación'),
            'ancho': ('Ancho del mueble'),
            'largo': ('Largo del mueble'),
            'alto': ('Alto del mueble'),
            'volumen_en_camion': ('Volumen en el camion del mueble'),
            'predefinido': ('¿Es predefinido del mueble?')
        }


class MueblePorAmbienteForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = MueblePorAmbiente
        fields = '__all__'

mueble/templates/mueble_add.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Agregar un mueble'

{% endblock titulo_ficha %}

{% block paginacionFicha %}{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script>
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$('#id_mueble').focus();
</script>

<style>.paginacionEdit{height: 0;}</style>

{% endblock jsFicha %}

mueble/templates/mueble_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha del mueble: {{form.mueble.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if mueble_previous %}

<li class="anterior">
  <a href="{% url 'umuebles:edit_mueble' mueble_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>
{% else %}

<li class="anteriorBloqueado">
  <a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a>
</li>

{% endif %}

{% if mueble_next %}

<li class="siguiente">
  <a href="{% url 'umuebles:edit_mueble' mueble_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
  <a href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
var pos = $(tr).position();
tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.mueble.value}}');
tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.descripcion.value|truncatechars:"30"}}');
tr.children('td[id=td3_{{form.instance.pk}}]').text('{{form.trasladable.value|yesno:"Trasladable,No trasladable"}}');
tr.children('td[id=td4_{{form.instance.pk}}]').text('{{form.fragil.value|yesno:"Es fragil,No es fragil"}}');
tr.children('td[id=td5_{{form.instance.pk}}]').text('{{form.pesado.value|yesno:"Es pesado,No es pesado"}}');
tr.children('td[id=td6_{{form.instance.pk}}]').text('{{form.contenido_fragil.value|yesno:"Contenido fragil,Sin contenido fragil"}}');
tr.children('td[id=td7_{{form.instance.pk}}]').text('{{form.contenido_textil.value|yesno:"Contenido textil,Sin contenido textil"}}');
tr.children('td[id=td8_{{form.instance.pk}}]').text('{{mueble.tipo_de_mueble}}');
$(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
$('#id_mueble').focus();
</script>

{% endblock jsFicha %}

mueble/templates/muebleporambiente_lista.html
{% extends "base_lista.html" %}
<title>Mueble por ambiente</title>
{% block titulo_lista %}
<h2>Listado de Mueble por ambiente</h2>

<h6>Cantidad de Mueble por ambiente encontrados:
  <span class="badge" id="count_reg">

    {{ mueblesporambiente.count }}

  </span>
</h6>
{% endblock titulo_lista %}
{% block paginacion_lista %}

{% if request.GET.page == "0" %}

<li><a href="?page=1">Paginar</a></li>

{% else %}

{% if page_obj.has_previous %}

{% if request.GET.order_by %}

<li>
  <a href="?page={{ page_obj.previous_page_number }}&order_by={{request.GET.order_by}}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li>
  <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
  <a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
  <a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% endif %}

{% if request.GET.page == "1" %}

<li class="btn-disabled">
  <a href="?page=1&order_by={{request.GET.order_by}}">Primero...</a>
</li>

{% else %}

<li class="">
  <a href="?page=1&order_by={{request.GET.order_by}}">Primero...</a>
</li>

{% endif %}


{% for p in page_range2 %}

{% if p == page_obj.number %}

<li class="active">
  <a href="?page={{p}}&order_by={{request.GET.order_by}}">{{p}}</a>
</li>

{% else %}

<li>
  <a href="?page={{p}}&order_by={{request.GET.order_by}}">{{p}}</a>
</li>

{% endif %}


{% endfor %}

{% if page_obj.paginator.num_pages %}

{% if request.GET.page == ultimo %}

<li class="btn-disabled">
  <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}">...Ultimo</a>
</li>

{% else %}

<li class="">
  <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}">...Ultimo</a>
</li>

{% endif %}

{% endif %}

{% if page_obj.has_next %}

{% if request.GET.order_by %}

<li>
  <a href="?page={{ page_obj.next_page_number }}&order_by={{request.GET.order_by}}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li>
  <a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
  <a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
  <a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% endif %}

<li><a href="?page=0">Ver todo</a></li>

{% endif %}

{% endblock paginacion_lista %}
{% block lista %}

{% if mueblesporambiente %}

  <tr class="active">
    <th>
      mueble por ambiente
      {% if request.GET.page %}

        <a href="?order_by=especifiacion_de_mueble&page={{request.GET.page}}" id="especifiacion_de_mueble" class="glyphicon glyphicon-sort-by-alphabet btn-ordenarLista" data-placement="left" data-toggletooltip="tooltip" title="Asc">Asc</a>
        <a href="?order_by=-especifiacion_de_mueble&page={{request.GET.page}}" id="-especifiacion_de_mueble"  class="glyphicon glyphicon-sort-by-alphabet-alt btn-ordenarLista" data-placement="left" data-toggletooltip="tooltip" title="Desc">Desc</a>

      {% else %}

        <a href="?order_by=especifiacion_de_mueble" id="especifiacion_de_mueble" class="glyphicon glyphicon-sort-by-alphabet btn-ordenarLista" data-placement="left" data-toggletooltip="tooltip" title="Asc">Asc</a>
        <a href="?order_by=-especifiacion_de_mueble" id="-especifiacion_de_mueble"  class="glyphicon glyphicon-sort-by-alphabet-alt btn-ordenarLista" data-placement="left" data-toggletooltip="tooltip" title="Desc">Desc</a>

      {% endif %}

    </th>
    <th width="80px">Editar</th>
    <th width="80px">Eliminar</th>
  </tr>

  {% for i in mueblesporambiente %}

  <tr id="tr{{i.pk}}">
    <td>

      {{ i }}

    </td>
    <td width="80px">
      <a title="Editar" data-toggle="tooltip" data-placement="right" href="{% url 'umuebles:edit_muebleporambiente' i.pk %}?next={{request.get_full_path}}" class="glyphicon glyphicon-edit">Edit</a>
    </td>
    <td width="80px">
      <a title="Eliminar" data-toggle="tooltip" data-placement="right" href="{% url 'umuebles:eliminar_muebleporambiente' i.pk %}?next={{request.get_full_path}}" class="glyphicon glyphicon-edit">elim</a>
    </td>
  </tr>

  {% endfor %}

{% else %}


<tr><td> No se encontraron registros</td>
</tr>

{% endif %}

<script>
ocultarASCDesc('especifiacion_de_mueble');
</script>
{% endblock lista %}

mueble/templates/tipodemueble_add.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Agregar un tipo de mueble'

{% endblock titulo_ficha %}

{% block paginacionFicha %}{% endblock paginacionFicha %}

{% block ficha_basica %}

  {{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script>
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$('#id_tipo_de_mueble').focus();
</script>

<style>.paginacionEdit{height: 0;}</style>

{% endblock jsFicha %}

mueble/templates/tipodemueble_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha del tipo de mueble: {{form.tipo_de_mueble.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if tipodemueble_previous %}

<li class="anterior">
    <a href="{% url 'umuebles:edit_tipodemueble' tipodemueble_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">&larr; anterior</a>
</li>

{% endif %}

{% if tipodemueble_next %}

<li class="siguiente">
 <a href="{% url 'umuebles:edit_tipodemueble' tipodemueble_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">siguienete &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">siguienete &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
var pos = $(tr).position();
tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.tipo_de_mueble.value}}');
tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.descripcion.value|truncatechars:"30"}}');
$(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
$('#id_tipo_de_mueble').focus();
</script>

{% endblock jsFicha %}