api/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url, include
from api.views import ClienteViewSet
from rest_framework import routers


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'apiv01cliente', ClienteViewSet)

urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       )

mtvmcotizacionv02/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from mtvmcotizacionv02 import views

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from api.views import ClienteViewSet, PaisViewSet, \
    ProvinciaViewSet, TipoDeClienteViewSet, \
    CiudadViewSet, BarrioViewSet, CalleViewSet, \
    DireccionViewSet


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'api/v1/tipodecliente', TipoDeClienteViewSet)
router.register(r'api/v1/cliente', ClienteViewSet)
router.register(r'api/v1/pais', PaisViewSet)
router.register(r'api/v1/provincia', ProvinciaViewSet)
router.register(r'api/v1/ciudad', CiudadViewSet)
router.register(r'api/v1/barrio', BarrioViewSet)
router.register(r'api/v1/calle', CalleViewSet)
router.register(r'api/v1/direccion', DireccionViewSet)

urlpatterns = [
    url(r'^$', views.pantalla_inicial,
        name='pantalla_inicial'),
    url(r'^guia_de_estilo/',
        views.guia_de_estilo,
        name='guia_de_estilos'),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^direccion/',
        include('direccion.urls',
                namespace="udirecciones")),
    url(r'^ambiente/',
        include('ambiente.urls',
                namespace="uambientes")),
    url(r'^cliente/',
        include('cliente.urls',
                namespace="uclientes")),
    url(r'^contenedor/',
        include('contenedor.urls',
                namespace="ucontenedores")),
    url(r'^mueble/',
        include('mueble.urls',
                namespace="umuebles")),
    url(r'^gestiondedocumento/',
        include('gestiondedocumento.urls',
                namespace="ugestiondedocumentos")),
    url(r'^estadoderegistro/',
        include('estadoderegistro.urls',
                namespace="uestadoderegistros")),
    url(r'^complejidadriesgo/',
        include('complejidadriesgo.urls',
                namespace="ucomplejidadriesgos")),
    url(r'^mensaje/',
        include('mensaje.urls',
                namespace="umensajes")),
    url(r'^premisas/',
        include('premisas.urls',
                namespace="upremisas")),
    url(r'^promocion/',
        include('promocion.urls',
                namespace="upromociones")),
    url(r'^menu/',
        include('menu.urls',
                namespace="umenus")),
    url(r'^herramienta/',
        include('herramienta.urls',
                namespace="uherramientas")),
    url(r'^material/',
        include('material.urls',
                namespace="umateriales")),
    url(r'^servicio/',
        include('servicio.urls',
                namespace="uservicios")),
    url(r'^talonario/',
        include('talonario.urls',
                namespace="utalonarios")),
    url(r'^trabajador/',
        include('trabajador.urls',
                namespace="utrabajadores")),
    url(r'^vehiculo/',
        include('vehiculo.urls',
                namespace="uvehiculos")),
    url(r'^widget/',
        include('widget.urls',
                namespace="uwidgets")),
    url(r'^cotizacionweb/',
        include('cotizacionweb.urls',
                namespace="ucotizacionesweb")),
    url(r'^almacen/',
        include('almacen.urls',
                namespace="ualmacenes")),
    url(r'^cotizador/',
        include('cotizador.urls',
                namespace="ucotizadores")),
    url(r'^usuario/',
        include('usuario.urls',
                namespace="uusuarios")),
    url(r'^notificacion/',
        include('notificacion.urls',
                namespace="unotificaciones")),
    url(r'^api/',
        include('api.urls',
                namespace="uapis")),
    url(r'^chaining/',
        include('smart_selects.urls')),
    url(r'^sidebarUpdate/$',
        'mtvmcotizacionv02.views.sidebarUpdate',
        name='sidebarUpdate'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls',
                namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^static/(?P<path>.*)$',
                                'django.views.static.serve',
                                {'document_root': settings.STATICFILES_DIRS}),)

premisas/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url
from premisas.views import EmpresaListView, EmpresaView, \
    EmpresaUpdate, EmpresaDelete, PersonalizacionVisualListView, \
    PersonalizacionVisualView, PersonalizacionVisualUpdate, \
    PersonalizacionVisualDelete, VarianteVisualListView, \
    VarianteVisualCreateView, VarianteVisualUpdate, \
    VarianteVisualDelete, DatosPrecargadoListView, \
    DatosPrecargadoView
from premisas import views


urlpatterns = patterns('',
                       url(r'^empresa/$',
                           EmpresaListView.as_view(),
                           name='list_empresa'),
                       url(r'^empresa/nuevo/',
                           EmpresaView.as_view(),
                           name='add_empresa'),
                       url(r'^empresa/editar/(?P<pk>\d+)/$',
                           EmpresaUpdate.as_view(),
                           name='edit_empresa'),
                       url(r'^empresa/eliminar/(?P<pk>\d+)/$',
                           EmpresaDelete.as_view(),
                           name='eliminar_empresa'),
                       url(r'^personalizacion_visual/$',
                           PersonalizacionVisualListView.as_view(),
                           name='list_personalizacionvisual'),
                       url(r'^personalizacion_visual/nuevo/',
                           PersonalizacionVisualView.as_view(),
                           name='add_personalizacionvisual'),
                       url(r'^personalizacion_visual/editar/(?P<pk>\d+)/$',
                           PersonalizacionVisualUpdate.as_view(),
                           name='edit_personalizacionvisual'),
                       url(r'^personalizacion_visual/eliminar/(?P<pk>\d+)/$',
                           PersonalizacionVisualDelete.as_view(),
                           name='eliminar_personalizacionvisual'),
                       url(r'^variante_visual/$',
                           VarianteVisualListView.as_view(),
                           name='list_variantevisual'),
                       url(r'^variante_visual/nuevo/',
                           VarianteVisualCreateView.as_view(),
                           name='add_variantevisual'),
                       url(r'^variante_visual/editar/(?P<pk>\d+)/$',
                           VarianteVisualUpdate.as_view(),
                           name='edit_variantevisual'),
                       url(r'^variante_visual/eliminar/(?P<pk>\d+)/$',
                           VarianteVisualDelete.as_view(),
                           name='eliminar_variantevisual'),
                       url(r'^datos_precargado/$',
                           DatosPrecargadoListView.as_view(),
                           name='list_datosprecargado'),
                       url(r'^datos_precargado/nuevo/',
                           DatosPrecargadoView.as_view(),
                           name='add_datosprecargado'),
                       url(r'^model/exchange/(?P<model>\w+)/$',
                           views.exchange_fields,
                           name='exchange_fields'),
                       )

premisas/models.py
from django.db import models
from django.contrib.auth.models import User

VISIBILIDAD_CHOICES = (
    (1, 'Visible'),
    (2, 'No visible'),
    (3, 'Nunca visible'),
    )


# Create your models here.
class Empresa(models.Model):
    """docstring for Empresa"""
    codigo = models.CharField(max_length=10)
    empresa = models.CharField(max_length=250)
    telefonos = models.CharField(max_length=250)
    direccion = models.CharField(max_length=250)
    sitio_web = models.URLField()
    correo = models.EmailField()
    responsable = models.CharField(max_length=250, null=True, blank=True)
    cuit = models.CharField(max_length=100, null=True, blank=True)
    logo = models.ImageField(upload_to='static/img/')
    telefono_call_center = models.CharField(max_length=100)

    def __str__(self):
        return self.empresa


class PersonalizacionVisual(models.Model):
    """docstring for PersonalizacionVisual"""
    usuario = models.ForeignKey(User)
    tipo = models.CharField(max_length=250)
    valor = models.CharField(max_length=100)

    def __str__(self):
        return u' %s - %s' % (self.usuario, self.tipo)

    class Meta:
        verbose_name = "Personalización Visual"
        verbose_name_plural = "Personalizaciones Visuales"
        unique_together = (("usuario", "tipo"),)


class VarianteVisual(models.Model):
    """docstring for VarianteVisual"""
    usuario = models.ForeignKey(User)
    nombre = models.CharField(max_length=100, unique=True)
    model = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Variente Visual"
        verbose_name_plural = "Variantes Visuales"


class VarianteVisualDetalle(models.Model):
    """docstring for VarianteVisualDetalle"""
    variante_visual = models.ForeignKey(VarianteVisual)
    campo = models.CharField(max_length=100)
    visibilidad = models.IntegerField(choices=VISIBILIDAD_CHOICES, default=1)

    def __str__(self):
        return u' %s - %s' % (self.variante_visual, self.campo)

    class Meta:
        verbose_name = "Detalle de la variente visual"
        verbose_name_plural = "Detalle de las variantes visuales"


class DatosPrecargado(models.Model):
    """docstring for DatosPrecargado"""
    nombre_app = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    dato = models.CharField(max_length=100)
    tipo_de_dato = models.CharField(max_length=100)
    valor = models.CharField(max_length=100)

    def __str__(self):
        return u' %s - %s' % (self.nombre_app, self.model, self.dato)

    class Meta:
        verbose_name = "Dato precargado"
        verbose_name_plural = "Datos precargados"


class Moneda(models.Model):
    """docstring for Moneda"""
    moneda = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return self.moneda

    class Meta:
        verbose_name = "Moneda"
        verbose_name_plural = "Monedas"

premisas/forms.py
"""
Docstring documentación pendiente

"""
from premisas.models import Empresa, PersonalizacionVisual, \
    VarianteVisual, VarianteVisualDetalle, DatosPrecargado
from base.forms import BaseFormMd, SelectMD
from djangular.forms import NgModelFormMixin, NgModelForm
from django.forms.models import inlineformset_factory
from django.forms import ModelForm, Select, ModelChoiceField, TextInput, NumberInput, RadioSelect, Textarea
from django.contrib.contenttypes.models import ContentType
from django import forms


class EmpresaForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = Empresa
        fields = '__all__'
        widgets = {
            'codigo': TextInput(attrs={'required': 'required', 'tabindex':'1'}),
            'empresa': TextInput(attrs={'required': 'required', 'tabindex': '2'}),
            'telefonos': NumberInput(attrs={'required': 'required', 'tabindex': '3'}),
            'direccion': Textarea(attrs={'tabindex': '4', 'cols': '1', 'rows': '1'}),
            'sitio_web': Textarea(attrs={'tabindex': '5', 'cols': '1', 'rows': '1'}),
            'correo': Textarea(attrs={'tabindex': '6', 'cols': '1', 'rows': '1'}),
            'telefono_call_center': NumberInput(attrs={'required': 'required'})
            }
        labels = {
            'codigo': ('Código de la empresa'),
            'empresa': ('Nombre de la empresa'),
            'telefonos': ('Teléfono de la empresa'),
            'direccion': ('Dirección de la empresa'),
            'sitio_web': ('Sitio web de la empresa'),
            'correo': ('Correo de la empresa'),
            'responsable': ('Responsable de la empresa'),
            'cuit': ('Cuit de la empresa'),
            'logo': ('Logo de la empresa'),
            'telefono_call_center': ('Teléfono del call center')
            }


class PersonalizacionVisualForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = PersonalizacionVisual
        fields = '__all__'
        widgets = {
            'usuario': Select(attrs={'required': 'required', 'tabindex': '1'}),
            'tipo': Textarea(attrs={'required': 'required', 'tabindex': '2', 'cols': '1', 'rows': '1'}),
            'valor': TextInput(attrs={'required': 'required', 'tabindex': '3'})
        }
        labels = {
            'usuario': ('Nombre del usuario'),
            'tipo': ('Tipo de personalización'),
            'valor': ('Valor de personalización')
            }


class VarianteVisualForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    model_choices = [(content.model, content.model) for content in ContentType.objects.all()]
    model = forms.ChoiceField(
        widget=Select(attrs={'ng-change': 'selectChanged()'}),
        label='Nombre del model',
        choices=model_choices)

    class Meta:
        model = VarianteVisual
        fields = 'nombre', 'model', 'usuario'
        widgets = {
            'usuario': Select(attrs={'required': 'required', 'tabindex': '1'}),
            'nombre': Textarea(attrs={'required': 'required', 'tabindex': '2', 'cols': '1', 'rows': '1'}),
            'model': TextInput(attrs={'required': 'required', 'tabindex': '3'})
        }
        labels = {
            'usuario': ('Usuario'),
            'nombre': ('Nombre de la variante'),
            'model': ('Nombre del model')
            }

VarianteVisualDetalleFormSet = inlineformset_factory(VarianteVisual,
                                                     VarianteVisualDetalle, widgets={'visibilidad': RadioSelect()} ,
                                                     fields=('campo', 'visibilidad'), extra=1)


class DatosPrecargadoForm(NgModelFormMixin, NgModelForm, BaseFormMd):
    """
    Docstring documentación pendiente
    """
    nombreapp_choices = [(content['app_label'], content['app_label']) for content in ContentType.objects.values('app_label').distinct().order_by()]
    lista_model = ModelChoiceField(ContentType.objects, widget=Select(attrs={'class': 'form-control'}), empty_label=None, label='Model:')
    nombre_app = forms.ChoiceField(
        widget=Select(attrs={'class': 'form-control'}),
        label='Nombre de la app',
        choices=nombreapp_choices)

    dato = forms.ChoiceField(
        widget=Select(attrs={'class': 'form-control'}),
        label='Dato',
        choices=())

    class Meta:
        model = DatosPrecargado
        fields = '__all__'

premisas/templates/datosprecargado_lista.html
{% extends "base_lista.html" %}

{% block titulo %}

Datos precargado

{% endblock titulo %}

{% block titulo_lista %}

<h2>Listado de Datos precargados</h2>

<h6>Cantidad de Datos precargados encontrados:
    <span class="badge" id="count_reg">

        {{ datosprecargados.count }}

    </span>
</h6>

{% endblock titulo_lista %}

{% block paginacion_lista %}

{% if request.GET.page == "0" %}

<li><a href="?page=1">Paginar</a></li>

{% else %}

{% if page_obj.has_previous %}

{% if request.GET.order_by %}

<li>
    <a href="?page={{ page_obj.previous_page_number }}&order_by={{request.GET.order_by}}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li>
    <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% else %}



<li class="btn-disabled">
    <a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>



{% endif %}

{% if request.GET.page == "1" %}

<li class="btn-disabled">
    <a href="?page=1&order_by={{request.GET.order_by}}">Primero...</a>
</li>

{% else %}

<li class="">
    <a href="?page=1&order_by={{request.GET.order_by}}">Primero...</a>
</li>

{% endif %}

{% for p in page_range2 %}

{% if p == page_obj.number %}

<li class="active">
    <a href="?page={{p}}&order_by={{request.GET.order_by}}">{{p}}</a>
</li>

{% else %}

<li>
    <a href="?page={{p}}&order_by={{request.GET.order_by}}">{{p}}</a>
</li>

{% endif %}

{% endfor %}

{% if page_obj.paginator.num_pages %}

{% if request.GET.page == ultimo %}

<li class="btn-disabled">
    <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}">...Ultimo</a>
</li>

{% else %}

<li class="">
    <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}">...Ultimo</a>
</li>

{% endif %}

{% endif %}

{% if page_obj.has_next %}

{% if request.GET.order_by %}

<li>
    <a href="?page={{ page_obj.next_page_number }}&order_by={{request.GET.order_by}}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li>
    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
    <a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
    <a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% endif %}

<li><a href="?page=0">Ver todo</a></li>

{% endif %}

{% endblock paginacion_lista %}

{% block lista %}

{% if datosprecargados %}

<tr class="active">
    <th>
        Nombre de la app

        {% if request.GET.page %}

        <a href="?order_by=nombre_app&page={{request.GET.page}}" id="nombre_app" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente"></a>
        <a href="?order_by=-nombre_app&page={{request.GET.page}}" id="-nombre_app"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente"></a>

        {% else %}

        <a href="?order_by=nombre_app" id="nombre_app" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente"></a>
        <a href="?order_by=-nombre_app" id="-nombre_app"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente"></a>

        {% endif %}

    </th>
    <th>
        model

        {% if request.GET.page %}

        <a href="?order_by=model&page={{request.GET.page}}" id="model" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente"></a>
        <a href="?order_by=-model&page={{request.GET.page}}" id="-model"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente"></a>

        {% else %}

        <a href="?order_by=model" id="model" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente"></a>
        <a href="?order_by=-model" id="-model"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente"></a>

        {% endif %}

    </th>
    <th>
        dato

        {% if request.GET.page %}

        <a href="?order_by=dato&page={{request.GET.page}}" id="dato" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente"></a>
        <a href="?order_by=-dato&page={{request.GET.page}}" id="-dato"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente"></a>

        {% else %}

        <a href="?order_by=dato" id="dato" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente"></a>
        <a href="?order_by=-dato" id="-dato"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente"></a>

        {% endif %}

    </th>
    <th class="controlLista">Editar</th>
    <th class="controlLista">Eliminar</th>
</tr>

{% for i in datosprecargados %}

<tr id="tr{{i.pk}}">
    <td>

        {{ i.nombre_app }}

    </td>
    <td>

        {{ i.model }}

    </td>
    <td>

        {{ i.dato }}

    </td>
    <td>
        <a title="Editar" data-toggletooltip="tooltip" data-placement="left" href="{% url 'upremisas:edit_personalizacionvisual' i.pk %}?next={{request.get_full_path}}" class="glyphicon glyphicon-edit"></a>
    </td>
    <td>
        <a title="Eliminar" data-toggletooltip="tooltip" data-placement="left" href="{% url 'upremisas:eliminar_personalizacionvisual' i.pk %}?next={{request.get_full_path}}" class="glyphicon glyphicon-remove"></a>
    </td>
</tr>

{% endfor %}

{% else %}

<tr>

    <td> No se encontraron registros </td>
</tr>

{% endif %}

<script>
    $(document).on('ready',function(){
        ocultarASCDesc('nombre_app');
        ocultarASCDesc('model');
        ocultarASCDesc('dato');
    })
</script>

{% endblock lista %}

premisas/templates/empresa_add.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Agregar una empresa'

{% endblock titulo_ficha %}

{% block paginacionFicha %}{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script>
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
</script>

<style>.paginacionEdit{height: 0;}</style>

{% endblock jsFicha %}

premisas/templates/empresa_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha de empresa {{form.empresa.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if empresa_previous %}

<li class="anterior">
    <a href="{% url 'upremisas:edit_empresa' empresa_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado">
  <a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a>
</li>

{% endif %}

{% if empresa_next %}

<li class="siguiente">
    <a href="{% url 'upremisas:edit_empresa' empresa_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
  <a href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
var pos = $(tr).position();
tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.codigo.value}}');
tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.empresa.value}}');
tr.children('td[id=td3_{{form.instance.pk}}]').text('{{form.telefonos.value}}');
tr.children('td[id=td4_{{form.instance.pk}}]').text('{{form.direccion.value|truncatechars:"30"}}');
tr.children('td[id=td5_{{form.instance.pk}}]').text('{{form.sitio_web.value|truncatechars:"30"}}');
tr.children('td[id=td6_{{form.instance.pk}}]').text('{{form.correo.value|truncatechars:"30"}}');
tr.children('td[id=td7_{{form.instance.pk}}]').text('{{form.responsable.value}}');
tr.children('td[id=td8_{{form.instance.pk}}]').text('{{form.cuit.value}}');
tr.children('td[id=td9_{{form.instance.pk}}]').text('{{form.logo.value}}');
tr.children('td[id=td10_{{form.instance.pk}}]').text('{{form.telefono_call_center.value}}');
$(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
</script>

{% endblock jsFicha %}

premisas/templates/personalizacionvisual_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha de la personalización visual: {{form.tipo.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if personalizacionvisual_previous %}

<li class="anterior">
    <a href="{% url 'upremisas:edit_personalizacionvisual' personalizacionvisual_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a>
</li>

{% endif %}

{% if personalizacionvisual_next %}

<li class="siguiente">
    <a href="{% url 'upremisas:edit_personalizacionvisual' personalizacionvisual_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
    <a ng-href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
    $(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
    $(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
    var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
    var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
    var pos = $(tr).position();
    tr.children('td[id=td1_{{form.instance.pk}}]').text('{{personalizacionvisual.usuario}}');
    tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.tipo.value|truncatechars:"30"}}');
    tr.children('td[id=td3_{{form.instance.pk}}]').text('{{form.valor.value}}');
    $(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
</script>

{% endblock jsFicha %}