api/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url, include
from api.views import ClienteViewSet
from rest_framework import routers


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'apiv01cliente', ClienteViewSet)

urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       )

material/urls.py
"""
Docstring pendiente para este documento
"""


from django.conf.urls import patterns, url
from material.views import TipoDeMaterialListView, TipoDeMaterialView, \
    TipoDeMaterialUpdate, TipoDeMaterialDelete, MaterialListView, \
    MaterialView, MaterialUpdate, MaterialDelete


urlpatterns = patterns('',
                       url(r'^$',
                           MaterialListView.as_view(),
                           name='list_material'),
                       url(r'^nuevo/',
                           MaterialView.as_view(),
                           name='add_material'),
                       url(r'^editar/(?P<pk>\d+)/$',
                           MaterialUpdate.as_view(),
                           name='edit_material'),
                       url(r'^eliminar/(?P<pk>\d+)/$',
                           MaterialDelete.as_view(),
                           name='eliminar_material'),
                       url(r'^tipo_de_material/$',
                           TipoDeMaterialListView.as_view(),
                           name='list_tipodematerial'),
                       url(r'^tipo_de_material/nuevo/',
                           TipoDeMaterialView.as_view(),
                           name='add_tipodematerial'),
                       url(r'^tipo_de_material/editar/(?P<pk>\d+)/$',
                           TipoDeMaterialUpdate.as_view(),
                           name='edit_tipodematerial'),
                       url(r'^tipo_de_material/eliminar/(?P<pk>\d+)/$',
                           TipoDeMaterialDelete.as_view(),
                           name='eliminar_tipodematerial'),
                       )

mtvmcotizacionv02/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from mtvmcotizacionv02 import views

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from api.views import ClienteViewSet, PaisViewSet, \
    ProvinciaViewSet, TipoDeClienteViewSet, \
    CiudadViewSet, BarrioViewSet, CalleViewSet, \
    DireccionViewSet


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'api/v1/tipodecliente', TipoDeClienteViewSet)
router.register(r'api/v1/cliente', ClienteViewSet)
router.register(r'api/v1/pais', PaisViewSet)
router.register(r'api/v1/provincia', ProvinciaViewSet)
router.register(r'api/v1/ciudad', CiudadViewSet)
router.register(r'api/v1/barrio', BarrioViewSet)
router.register(r'api/v1/calle', CalleViewSet)
router.register(r'api/v1/direccion', DireccionViewSet)

urlpatterns = [
    url(r'^$', views.pantalla_inicial,
        name='pantalla_inicial'),
    url(r'^guia_de_estilo/',
        views.guia_de_estilo,
        name='guia_de_estilos'),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^direccion/',
        include('direccion.urls',
                namespace="udirecciones")),
    url(r'^ambiente/',
        include('ambiente.urls',
                namespace="uambientes")),
    url(r'^cliente/',
        include('cliente.urls',
                namespace="uclientes")),
    url(r'^contenedor/',
        include('contenedor.urls',
                namespace="ucontenedores")),
    url(r'^mueble/',
        include('mueble.urls',
                namespace="umuebles")),
    url(r'^gestiondedocumento/',
        include('gestiondedocumento.urls',
                namespace="ugestiondedocumentos")),
    url(r'^estadoderegistro/',
        include('estadoderegistro.urls',
                namespace="uestadoderegistros")),
    url(r'^complejidadriesgo/',
        include('complejidadriesgo.urls',
                namespace="ucomplejidadriesgos")),
    url(r'^mensaje/',
        include('mensaje.urls',
                namespace="umensajes")),
    url(r'^premisas/',
        include('premisas.urls',
                namespace="upremisas")),
    url(r'^promocion/',
        include('promocion.urls',
                namespace="upromociones")),
    url(r'^menu/',
        include('menu.urls',
                namespace="umenus")),
    url(r'^herramienta/',
        include('herramienta.urls',
                namespace="uherramientas")),
    url(r'^material/',
        include('material.urls',
                namespace="umateriales")),
    url(r'^servicio/',
        include('servicio.urls',
                namespace="uservicios")),
    url(r'^talonario/',
        include('talonario.urls',
                namespace="utalonarios")),
    url(r'^trabajador/',
        include('trabajador.urls',
                namespace="utrabajadores")),
    url(r'^vehiculo/',
        include('vehiculo.urls',
                namespace="uvehiculos")),
    url(r'^widget/',
        include('widget.urls',
                namespace="uwidgets")),
    url(r'^cotizacionweb/',
        include('cotizacionweb.urls',
                namespace="ucotizacionesweb")),
    url(r'^almacen/',
        include('almacen.urls',
                namespace="ualmacenes")),
    url(r'^cotizador/',
        include('cotizador.urls',
                namespace="ucotizadores")),
    url(r'^usuario/',
        include('usuario.urls',
                namespace="uusuarios")),
    url(r'^notificacion/',
        include('notificacion.urls',
                namespace="unotificaciones")),
    url(r'^api/',
        include('api.urls',
                namespace="uapis")),
    url(r'^chaining/',
        include('smart_selects.urls')),
    url(r'^sidebarUpdate/$',
        'mtvmcotizacionv02.views.sidebarUpdate',
        name='sidebarUpdate'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls',
                namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^static/(?P<path>.*)$',
                                'django.views.static.serve',
                                {'document_root': settings.STATICFILES_DIRS}),)

material/models.py
from django.db import models
from almacen.models import Unidad
from django.contrib.auth.models import User
from servicio.models import Servicio


# Create your models here.
class TipoDeMaterial(models.Model):
    """docstring for TipoDeMaterial"""
    def __init__(self, *args, **kwargs):
        super(TipoDeMaterial, self).__init__(*args, **kwargs)

    tipo_de_material = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.tipo_de_material

    class Meta:
        verbose_name = "Tipo de material "
        verbose_name_plural = "Tipos de materiales"
        ordering = ["tipo_de_material"]


class Material(models.Model):
    """docstring for Material"""
    def __init__(self, *args, **kwargs):
        super(Material, self).__init__(*args, **kwargs)

    material = models.CharField(max_length=100)
    descripcion = models.TextField()
    tipo_de_material = models.ForeignKey(TipoDeMaterial)
    unidad_de_consumo = models.ForeignKey(Unidad, related_name='und_consumo')
    unidad_de_venta = models.ForeignKey(Unidad, related_name='und_venta')
    relacion_consumo_venta = models.DecimalField(max_digits=9, decimal_places=2)
    ancho = models.DecimalField(max_digits=7, decimal_places=2)
    largo = models.DecimalField(max_digits=7, decimal_places=2)
    alto = models.DecimalField(max_digits=7, decimal_places=2)
    peso_unidad_consumo_kg = models.DecimalField(max_digits=7, decimal_places=2)
    cotizable = models.BooleanField(default=None)

    def __str__(self):
        return self.material

    def _get_volumen(self):
        return round((self.ancho*self.alto*self.largo)/1000000, 3)
    volumen = property(_get_volumen)

    def _get_densidad(self):
        #falta por definir la fórmula
        return round((self.ancho*self.alto*self.largo)/1000000, 3)
    densidad = property(_get_densidad)

    class Meta:
        verbose_name = "Material "
        verbose_name_plural = "Materiales"
        ordering = ["material"]


class PrecioDeMaterial(models.Model):
    """docstring for PrecioDeMaterial"""
    def __init__(self, *args, **kwargs):
        super(PrecioDeMaterial, self).__init__(*args, **kwargs)

    material = models.ForeignKey(Material)
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    fecha_desde = models.DateField()
    fecha_hasta = models.DateField()
    infinito = models.BooleanField(default=None)
    user_preparador = models.ForeignKey(User, related_name='user_preparador_material')
    fecha_preparacion = models.DateField(auto_now_add=True)
    user_aprobador = models.ForeignKey(User, null=True, blank=True, related_name='user_aprobador_material')
    fecha_aprobacion = models.DateField(blank=True)
    aprobado = models.BooleanField(default=None)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = "Precio del material"
        verbose_name_plural = "Precios del material"


class MaterialesPorServicio(models.Model):
    """docstring for MaterialesPorServicio"""
    def __init__(self, *args, **kwargs):
        super(MaterialesPorServicio, self).__init__(*args, **kwargs)

    servicio = models.ForeignKey(Servicio)
    material = models.ForeignKey(Material)
    cantidad = models.DecimalField(max_digits=9, decimal_places=2)
    calculo = models.CharField(max_length=200)

    def __str__(self):
        return u' %s - %s' % (self.servicio, self.material)

    class Meta:
        verbose_name = "Material por servicio"
        verbose_name_plural = "Materiales por servicio"
        ordering = ["servicio", "material"]

material/forms.py
"""
Docstring documentación pendiente

"""
from material.models import Material, TipoDeMaterial, \
    PrecioDeMaterial, MaterialesPorServicio
from base.forms import BaseFormMd
from djangular.forms import NgModelFormMixin, NgModelForm
from django.forms.models import inlineformset_factory
from base.forms import BaseFormMd, SelectMD, Checkbox
from django.forms import ModelForm, TextInput, Textarea, Select

class MaterialForm(ModelForm):
    """
    Docstring documentación pendiente
    """

    def __init__(self, *args, **kwargs):
        super(MaterialForm, self).__init__(*args, **kwargs)
        self.fields['tipo_de_material'].empty_label = "Seleccione el tipo de material"
        self.fields['unidad_de_consumo'].empty_label = "Seleccione la unidad de consumo"
        self.fields['unidad_de_venta'].empty_label = "Seleccione la unidad de venta"

    class Meta:
        model = Material
        fields = 'tipo_de_material', 'unidad_de_consumo', 'unidad_de_venta', 'material', 'descripcion', 'relacion_consumo_venta', 'ancho', 'largo', 'alto', 'peso_unidad_consumo_kg', 'cotizable'
        labels = {
            'tipo_de_material': ('Nombre del tipo de material'),
            'descripcion': ('Descripción del material'),
            'unidad_de_consumo': ('Unidad de consumo del material'),
            'unidad_de_venta': ('Unidad de venta del material'),
            'material': ('Nombre del material'),
            'relacion_consumo_venta': ('Relación de consumo del material'),
            'ancho': ('Ancho del material (cm)'),
            'largo': ('Largo del material (cm)'),
            'alto': ('Alto del material (cm)'),
            'peso_unidad_consumo_kg': ('Peso de consumo del material (Kg)'),
            'cotizable': ('¿El material es cotizable?')
        }
        widgets = {
            'tipo_de_material': Select(attrs={'required': 'required', 'tabindex': '1', 'ng-change': 'onChange()'}),
            'unidad_de_consumo': Select(attrs={'required': 'required', 'tabindex': '1', 'ng-change': 'onChange()'}),
            'unidad_de_venta': Select(attrs={'required': 'required', 'tabindex': '1', 'ng-change': 'onChange()'}),
            'material': TextInput(attrs={'required': 'required', 'tabindex':'2'}),
            'descripcion': Textarea(attrs={'tabindex': '3', 'cols': '1', 'rows': '1'}),
            }


class TipoDeMaterialForm(ModelForm):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = TipoDeMaterial
        fields = '__all__'
        labels = {
            'tipo_de_material': ('Nombre del tipo de material'),
            'descripcion': ('Descripción del tipo de material')
        }
        widgets = {
            'tipo_de_material': TextInput(attrs={'required': 'required', 'tabindex':'1'}),
            'descripcion': Textarea(attrs={'tabindex': '2', 'cols': '1', 'rows': '1'}),
            }


class PrecioDeMaterialForm(NgModelFormMixin, NgModelForm, BaseFormMd):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = PrecioDeMaterial
        fields = '__all__'


class MaterialesPorServicioForm(NgModelFormMixin, NgModelForm, BaseFormMd):
    """
    Docstring documentación pendiente
    """
    class Meta:
        model = MaterialesPorServicio
        fields = '__all__'

material/templates/material_add.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Agregar un material'

{% endblock titulo_ficha %}

{% block paginacionFicha %}{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script>
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
</script>

<style>.paginacionEdit{height: 0;}</style>

{% endblock jsFicha %}

material/templates/material_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha del material: {{form.material.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if material_previous %}

<li class="anterior">
    <a href="{% url 'umateriales:edit_material' material_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado"><a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a></li>

{% endif %}

{% if material_next %}

<li class="siguiente">
    <a href="{% url 'umateriales:edit_material' material_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
    $(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
    $(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
    var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
    tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.material.value}}');
    tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.descripcion.value|truncatechars:"30"}}');
    tr.children('td[id=td3_{{form.instance.pk}}]').text('{{form.relacion_consumo_venta.value}}');
    tr.children('td[id=td4_{{form.instance.pk}}]').text('{{form.ancho.value}}');
    tr.children('td[id=td5_{{form.instance.pk}}]').text('{{form.largo.value}}');
    tr.children('td[id=td6_{{form.instance.pk}}]').text('{{form.alto.value}}');
    tr.children('td[id=td7_{{form.instance.pk}}]').text('{{form.peso_unidad_consumo_kg.value}}');
    tr.children('td[id=td8_{{form.instance.pk}}]').text('{{material.unidad_de_consumo}}');
    tr.children('td[id=td9_{{form.instance.pk}}]').text('{{material.unidad_de_venta}}');
    tr.children('td[id=td10_{{form.instance.pk}}]').text('{{form.cotizable.value|yesno:"Es cotizable,No cotizable"}}');
    tr.children('td[id=td11_{{form.instance.pk}}]').text('{{material.tipo_de_material}}');
    $(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
</script>

{% endblock jsFicha %}

material/templates/tipodematerial_add.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Agregar un tipo de material'

{% endblock titulo_ficha %}

{% block paginacionFicha %}{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script>
$(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
$('#id_tipo_de_material').focus();
</script>

<style>.paginacionEdit{height: 0;}</style>

{% endblock jsFicha %}

material/templates/tipodematerial_edit.html
{% extends "base_ficha.html" %}

{% block titulo_ficha %}

'Ficha el tipo de material: {{form.tipo_de_material.value|lower}}'

{% endblock titulo_ficha %}

{% block paginacionFicha %}

{% if tipodematerial_previous %}

<li class="anterior">
    <a href="{% url 'umateriales:edit_tipodematerial' tipodematerial_previous.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">&larr; Anterior</a>
</li>

{% else %}

<li class="anteriorBloqueado"><a href="#" ng-disabled="true" tabindex="-1">&larr; Anterior</a></li>

{% endif %}

{% if tipodematerial_next %}

<li class="siguiente">
    <a href="{% url 'umateriales:edit_tipodematerial' tipodematerial_next.id %}?next={{request.GET.next}}{% if request.GET.page %}&page={{request.GET.page}}{% elif request.GET.order_by %}&order_by={{request.GET.order_by}}{% endif %}" tabindex="-1">Siguiente &rarr;</a>
</li>

{% else %}

<li class="siguienteBloqueado">
    <a href="#" ng-disabled="true" tabindex="-1">Siguiente &rarr;</a>
</li>

{% endif %}

{% endblock paginacionFicha %}

{% block ficha_basica %}

{{ form.as_p }}

{% endblock ficha_basica %}

{% block jsFicha %}

<script type="text/javascript">
    $(parent.document.getElementsByClassName("btnFicha")).removeClass('seleccion');
    $(parent.document.getElementById("tr"+{{form.instance.pk}})).addClass('seleccion');
    var tr = $(parent.document.getElementById("tr"+{{form.instance.pk}}));
    var scroll = $(parent.document.getElementsByClassName("page-content-wrapper"));
    var pos = $(tr).position();
    tr.children('td[id=td1_{{form.instance.pk}}]').text('{{form.tipo_de_material.value}}');
    tr.children('td[id=td2_{{form.instance.pk}}]').text('{{form.descripcion.value|truncatechars:"30"}}');
    $(scroll).animate({ scrollTop: pos.top - 250 }, 1000);
    $('#id_tipo_de_material').focus();
</script>

{% endblock jsFicha %}

material/templates/tipodematerial_lista.html
{% extends "base_lista.html" %}

{% block titulo %}

Material

{% endblock titulo %}

{% block titulo_lista %}

<h2>Listado de tipos de materiales</h2>
 <h6>Cantidad de tipos de materiales encontrados:
    <span class="numRegistro" id="count_reg">

        {{ tiposdemateriales.count }}

    </span>
</h6>

{% endblock titulo_lista %}

{% block paginacion_lista %}

{% if request.GET.page == "0" %}

<li><a href="?page=1">Paginar</a></li>

{% else %}

{% if page_obj.has_previous %}

{% if request.GET.order_by %}

<li>
  <a href="?page={{ page_obj.previous_page_number }}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li>
  <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
  <a href="#" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
  <a href="#" aria-label="Previous" tabindex="-1"><span aria-hidden="true">&laquo;</span></a>
</li>

{% endif %}

{% endif %}

{% if request.GET.page == "1" %}

<li class="btn-disabled">
  <a href="?page=1&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">Primero...</a>
</li>

{% else %}

<li class="">
  <a href="?page=1&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">Primero...</a>
</li>

{% endif %}

{% for p in page_range2 %}

{% if p == page_obj.number %}

<li class="active">
  <a href="?page={{p}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">{{p}}</a>
</li>

{% else %}

<li>
  <a href="?page={{p}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">{{p}}</a>
</li>

{% endif %}

{% endfor %}

{% if page_obj.paginator.num_pages %}

{% if request.GET.page == ultimo %}

<li class="btn-disabled">
  <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">...Ultimo</a>
</li>

{% else %}

<li class="">
  <a href="?page={{page_obj.paginator.num_pages}}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" tabindex="-1">...Ultimo</a>
</li>

{% endif %}

{% endif %}

{% if page_obj.has_next %}

{% if request.GET.order_by %}

<li>
  <a href="?page={{ page_obj.next_page_number }}&order_by={{request.GET.order_by}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li>
  <a href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% else %}

{% if request.GET.order_by %}

<li class="btn-disabled">
  <a href="#" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% else %}

<li class="btn-disabled">
  <a href="#" aria-label="Next" tabindex="-1"><span aria-hidden="true">&raquo;</span></a>
</li>

{% endif %}

{% endif %}

<li><a href="?page=0" tabindex="-1">Ver todo</a></li>

{% endif %}

{% endblock paginacion_lista %}

{% block lista %}

{% if tiposdemateriales %}

<tr class="active">
    <th>
        Nombre del tipo de material

        {% if request.GET.page %}

        {% if request.GET.order_by == "tipo_de_material" %}

        <a href="?order_by=-tipo_de_material&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-tipo_de_material"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=tipo_de_material&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="tipo_de_material" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% else %}

        {% if request.GET.order_by == "tipo_de_material" %}

        <a href="?order_by=-tipo_de_material&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-tipo_de_material"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=tipo_de_material&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="tipo_de_material" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% endif %}

    </th>
    <th>
        Descripción del tipo de material

        {% if request.GET.page %}

        {% if request.GET.order_by == "descripcion" %}

        <a href="?order_by=-descripcion&page={{request.GET.page}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-descripcion"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=descripcion&page={{request.GET.page}}" id="descripcion" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% else %}

        {% if request.GET.order_by == "descripcion" %}

        <a href="?order_by=-descripcion{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="-descripcion"  class="descendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Descendente" tabindex="-1"></a>

        {% else %}

        <a href="?order_by=descripcion{% if request.GET.search %}&search={{request.GET.search}}{% endif %}" id="descripcion" class="ascendenteAlfabetico" data-placement="left" data-toggletooltip="tooltip" title="Ascendente" tabindex="-1"></a>

        {% endif %}

        {% endif %}

    </th>
</tr>
<tbody>
{% for i in tiposdemateriales %}

<tr id="tr{{i.pk}}" data-url="{% url 'umateriales:edit_tipodematerial' i.pk %}?next={{request.get_full_path}}" class="btnFicha">
    <td id="td1_{{i.pk}}">

        {{ i.tipo_de_material }}

    </td>
    <td id="td2_{{i.pk}}">

        {{ i.descripcion|truncatechars:"30" }}

    </td>
    <td class="c_td">
      <a title="Eliminar" data-toggletooltip="tooltip" data-placement="left" data-url="{% url 'umateriales:eliminar_tipodematerial' i.pk %}?next={{request.get_full_path}}" data-id="{{ i.id }}" data-nombre="{{ i.tiposdemateriales }}" class="iconoRemover btnEliminar" data-toggle="modal" data-target="#modalEliminar" id="eliminar{{i.id}}"></a>
      <span class="iconoGrupoControl"></span>
    </td>
</tr>

{% endfor %}

{% else %}

<tr>
    <td> No se encontraron registros</td>
</tr>

{% endif %}

{% endblock lista %}